version: '3'
services:
    mongodb:        
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
            - MONGO_INITDB_ROOT_USERNAME=rpi
            - MONGO_INITDB_ROOT_PASSWORD=rpi
            - MONGO_INITDB_DATABASE=rpi
        ports:
            - "27017:27017"
        command: mongod --smallfiles --quiet